###
GET http://localhost:3000/actors

###
GET http://localhost:3000/actors/3

###
POST http://localhost:3000/actors

###
PATCH http://localhost:3000/actors/3
content-type: application/json

{
  "first_name": "C",
  "last_name": "D",
  "age": 12
}

###
DELETE http://localhost:3000/actors/

###
GET http://localhost:3000/movies

###
GET http://localhost:3000/movies/3

###
POST http://localhost:3000/movies

###
PATCH http://localhost:3000/movies/2
content-type: application/json

{
  "director": "J",
  "english": true
}

###
DELETE http://localhost:3000/movies/
